# Generated by Django 3.0.5 on 2020-04-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200430_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, primary_key=True, serialize=False),
        ),
    ]
