# Generated by Django 3.0.5 on 2020-04-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='accounts_token',
        ),
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
