# Generated by Django 3.0.5 on 2020-05-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='id_number',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.TextField(default=None, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
