# Generated by Django 3.0.5 on 2020-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200501_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id_number',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
