# Generated by Django 3.0.5 on 2020-05-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200501_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id_number',
        ),
        migrations.AddField(
            model_name='token',
            name='identifier',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.TextField(blank=True, default=None, max_length=8, null=True, unique=True),
        ),
    ]
