# Generated by Django 3.0.5 on 2020-05-01 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200501_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(code='invalid')]),
        ),
        migrations.AlterField(
            model_name='token',
            name='identifier',
            field=models.CharField(default=None, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.TextField(default=None, max_length=8, null=True, unique=True),
        ),
    ]
