# Generated by Django 3.0.5 on 2020-05-01 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200501_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='identifier',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.TextField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
