# Generated by Django 3.0.5 on 2020-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200501_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
