# Generated by Django 3.0.5 on 2020-05-01 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200501_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='identifier',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
