# Generated by Django 3.0.5 on 2020-05-10 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exercises.helper
import exercises.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('number', models.PositiveSmallIntegerField(default=None, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('release', models.DateTimeField(default=None, null=True)),
                ('deadline', models.DateTimeField(default=None, null=True)),
                ('description', models.FileField(upload_to=exercises.helper.get_description_path, validators=[exercises.validators.FileValidator(allowed_extensions=['md'], allowed_mimetypes=['text/markdown', 'text/plain', 'text/x-python'])])),
                ('tests', models.FileField(upload_to=exercises.helper.get_tests_path, validators=[exercises.validators.FileValidator(allowed_extensions=['py'], allowed_mimetypes=['text/python', 'text/x-python'])])),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True, unique=True)),
                ('file_hash', models.CharField(editable=False, max_length=40)),
                ('file', models.FileField(upload_to=exercises.helper.get_submission_path, validators=[exercises.validators.FileValidator(allowed_extensions=['py'], allowed_mimetypes=['text/x-python', 'text/plain'], max_size=3000, min_size=30)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file_hash', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.DateTimeField(auto_now_add=True, unique=True)),
                ('job_id', models.CharField(max_length=128)),
                ('test_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercises.Submission')),
            ],
            options={
                'ordering': ('-processed',),
            },
        ),
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('kind', models.CharField(choices=[('error', 'Error'), ('failure', 'Failure')], max_length=8)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.TestResult')),
            ],
        ),
    ]
