# Generated by Django 3.0.5 on 2020-05-10 23:32

from django.db import migrations, models
import exercises.helper
import exercises.storage
import exercises.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.FileField(storage=exercises.storage.OverwriteStorage(), upload_to=exercises.helper.get_description_path, validators=[exercises.validators.FileValidator(allowed_extensions=['md'], allowed_mimetypes=['text/markdown', 'text/plain', 'text/x-python'])]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tests',
            field=models.FileField(storage=exercises.storage.OverwriteStorage(), upload_to=exercises.helper.get_tests_path, validators=[exercises.validators.FileValidator(allowed_extensions=['py'], allowed_mimetypes=['text/python', 'text/x-python'])]),
        ),
    ]
