# Generated by Django 3.0.5 on 2020-04-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_delete_lol"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="lecture",),
        migrations.DeleteModel(name="Lecture",),
    ]
