# Generated by Django 3.0.5 on 2020-05-12 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200512_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='max_tests',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='first_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='first_failure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
