# Generated by Django 3.0.5 on 2020-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_auto_20200422_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="deadline",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="start_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
