# Generated by Django 3.0.5 on 2020-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200512_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='first_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='first_failure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
