# Generated by Django 3.0.5 on 2020-05-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20200512_1116'),
        ('exercises', '0005_auto_20200512_0840'),
    ]

    operations = [
    ]
