# Generated by Django 3.0.5 on 2020-04-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_auto_20200423_1628"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise", old_name="start_date", new_name="release_date",
        ),
    ]
