# Generated by Django 3.0.5 on 2020-05-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_merge_20200512_1118'),
        ('exercises', '0006_exercise_relevant'),
    ]

    operations = [
    ]
