# Generated by Django 3.0.5 on 2020-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0006_auto_20200423_1735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="deadline",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="release_date",
            field=models.DateTimeField(default=None),
        ),
    ]
