# Generated by Django 3.0.5 on 2020-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_merge_20200513_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='relevant',
            field=models.BooleanField(default=True, verbose_name='Fließt in die Wertung ein.'),
        ),
    ]
