# Generated by Django 3.0.5 on 2020-05-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20200514_1442'),
        ('exercises', '0008_auto_20200513_2014'),
    ]

    operations = [
    ]
