# Generated by Django 3.0.5 on 2020-04-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_auto_20200423_2025"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise", old_name="release_date", new_name="release",
        ),
    ]
