# Generated by Django 3.0.5 on 2020-05-14 18:02

from django.db import migrations, models
import exercises.helper
import exercises.storage


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20200514_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='resources',
            field=models.FileField(default=None, null=True, storage=exercises.storage.OverwriteStorage(), upload_to=exercises.helper.get_resources_path),
        ),
    ]
