# Generated by Django 3.0.5 on 2020-05-14 20:27

from django.db import migrations, models
import django.db.models.deletion
import exercises.helper
import exercises.storage


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200514_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='resources',
        ),
        migrations.CreateModel(
            name='ExerciseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, storage=exercises.storage.OverwriteStorage(), upload_to=exercises.helper.get_resources_path)),
                ('exercise', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='exercises.Exercise')),
            ],
        ),
    ]
