# Generated by Django 3.0.5 on 2020-04-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0011_submission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.User",
            ),
        ),
    ]
