# Generated by Django 3.0.5 on 2020-05-19 21:16

from django.db import migrations, models
import django.db.models.deletion
import exercises.helper
import exercises.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20200514_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=exercises.helper.get_submission_path, validators=[exercises.validators.FileValidator(allowed_extensions=['py'], allowed_mimetypes=['text/x-python', 'text/plain'], max_size=5000, min_size=30)]),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='first_error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='first_failure',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submission',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='exercises.Submission'),
        ),
    ]
