# Generated by Django 3.0.5 on 2020-04-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0012_auto_20200425_2304"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="user",),
        migrations.DeleteModel(name="User",),
    ]
