# Generated by Django 3.0.5 on 2020-05-22 05:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0013_auto_20200519_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.PositiveSmallIntegerField(default=None, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submission',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='exercises.Submission'),
        ),
    ]
