# Generated by Django 3.0.5 on 2020-04-27 03:38

import django.core.validators
from django.db import migrations, models
import exercises.models
import exercises.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_auto_20200425_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.PositiveSmallIntegerField(default=None, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=exercises.models._user_directory_path, validators=[exercises.validators.FileValidator(allowed_extensions=['py'], allowed_mimetypes=['text/x-python'], max_size=1000, min_size=30)]),
        ),
    ]
