# Generated by Django 3.0.5 on 2020-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_auto_20200427_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='markdown_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
