# Generated by Django 3.0.5 on 2020-04-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_auto_20200427_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='markdown_description',
            new_name='md_description',
        ),
    ]
