# Generated by Django 3.0.5 on 2020-04-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20200427_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='md_description',
            new_name='html_description',
        ),
    ]
