# Generated by Django 3.0.5 on 2020-05-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20200522_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresource',
            name='exercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
        ),
    ]
